name: Doxygen Generation

# Needs this to write to gh-pages branch.
permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  doxygen-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen generation
        uses: FreeRTOS/CI-CD-Github-Actions/doxygen-generation@main
